# To release:
#   GITHUB_TOKEN=*** goreleaser

builds:
- main: ./cmd/oras
  binary: ./oras
  env:
  - CGO_ENABLED=0
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  ldflags:
  # one-line ldflags to bypass the goreleaser bugs
  # the git tree state is guaranteed to be clean by goreleaser
  - -w -X github.com/deislabs/oras/internal/version.Version={{.Version}} -X github.com/deislabs/oras/internal/version.GitCommit={{.FullCommit}} -X github.com/deislabs/oras/internal/version.BuildMetadata= -X github.com/deislabs/oras/internal/version.GitTreeState=clean

archives:
  - format: tar.gz
    files:
      - LICENSE

signs:
  - artifacts: all
    args: ["--output", "${signature}", "--detach-sign", "--armor", "${artifact}"]
    signature: "${artifact}.asc"
