# Copyright The ORAS Authors.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: oras
version: git
summary: Package for the ORAS CLI tool
description: |
  A snap package for the ORAS CLI tool, which is used for managing OCI artifacts.
base: core22
confinement: strict
grade: devel

parts:
  oras:
    plugin: go
    source: .
    build-snaps:
      - go/1.20/stable
    build-packages:
      - make
    stage-packages:
      - ca-certificates
    override-build: |
      make "build-linux-$CRAFT_TARGET_ARCH"
      install -D -m755 bin/linux/$CRAFT_TARGET_ARCH/oras $CRAFT_PART_INSTALL/bin/oras

apps:
  oras:
    command: bin/oras
    plugs:
      - home
      - network
