version: '1.0'
stages:
- test
- build
- release
steps:

  UnitTest:
    title: Run unit tests
    stage: test
    image: golang:1.11-alpine
    commands:
    - apk add git make bash file
    - cf_export GOCACHE="${{CF_VOLUME_PATH}}/gocache"
    - cf_export GOPATH="${{CF_VOLUME_PATH}}/gopath"
    - make test
  BuildDockerImage:
    title: Build Docker image
    stage: build
    type: build
    image_name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    tag: ${{CF_BRANCH_TAG_NORMALIZED}}
  PushDockerImage:
    title: Push Docker image (latest)
    stage: release
    type: push
    candidate: ${{BuildDockerImage}}
    image_name: orasbot/${{CF_REPO_NAME}}
    registry: dockerhub
