name: build-debug

on:
  pull_request:
    branches:
      - debug

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup go environment
        uses: actions/setup-go@v1
        with:
          go-version: '1.18.1'
      - name: Build CLI
        run: make build-linux
      - name: Check version
        run: bin/linux/amd64/oras version
