# Copyright The ORAS Authors.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: release-snap

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'release version, like v1.2.0-beta.1'
        required: true
      isStable:
        type: boolean
        description: 'check for stable release'
        default: false

jobs:
  release-snap:
    strategy:
      matrix:
        arch:
        - 'amd64'
        - 'arm64'
        - 's390x'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: extract version
        id: version
        run: |
          if [[ "${{ github.event.inputs.isStable }}" == "true" ]]; then
            echo "release=stable" >> $GITHUB_OUTPUT
          else
            echo "release=candidate" >> $GITHUB_OUTPUT
          fi
          echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
      - name: make snapcraft
        run: |
          sed -i 's/{VERSION}/${{ steps.version.outputs.version }}/g' snapcraft.yaml
          sed -i 's/{ARCH}/${{ matrix.arch }}/g' snapcraft.yaml
          cat snapcraft.yaml

      - name: build
        id: build
        env:
          SNAPCRAFT_BUILD_ENVIRONMENT: lxd
          SNAPCRAFT_IMAGE_INFO: '{"build_url":"https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"}'
        run: |
          sudo chown root:root /
          sudo groupadd --force --system lxd
          sudo usermod --append --groups lxd "$(id -un)"
          if [ -x /snap/bin/lxd ]; then
            sudo snap refresh lxd
          else
            sudo snap install lxd
          fi
          sudo lxd init --auto
          sudo iptables -P FORWARD ACCEPT
          if [ -x /snap/bin/snapcraft ]; then
            sudo snap refresh --classic snapcraft
          else
            sudo snap install --classic snapcraft
          fi
          sudo -u "$(id -un)" -E /snap/bin/snapcraft
          echo "snap=$(ls ./*.snap)" >> "$GITHUB_OUTPUT"

      - name: publish
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
          SNAP_FILE: ${{ steps.build.outputs.snap }}
          SNAP_RELEASE: ${{ steps.version.outputs.release }}
        run: |
          /snap/bin/snapcraft upload "$SNAP_FILE" --release "$SNAP_RELEASE"

